apiVersion: v1
kind: Pod
metadata:
  name: pod-with-toleration
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "testing"
    effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: kind-worker2

